### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by carlganz** [carlganz/svrepmisc#2]
- [x] Make sure `quantreg::rq` is actually using complex survey design
- [x] Make sure t-values are correct for `svyrlm`
- [x] Make sure `truncreg::truncreg` is actually using complex survey design
- [x] Make sure `intReg::intReg` is actually using complex survey design
- [x] Make sure `svymultinom` consistent with SAS surveylogistic
- [ ] Make sure `truncreg` and `intReg` are consistent with Stata

**Comment by carlganz** [comment]
- `svyrlm` probably not svy adjusted
- `svytruncreg` and `svyintReg` exist in Stata so that's assuring
- `svyrq` is in survey documentation so that is also assuring

**Comment by carlganz** [comment]
# For 1.0
- [ ] Make sure the 7 current functions are statistically correct
- [ ] Write vignette

# For Future
- [ ] Add `predict`, `resid`, and `fitted` functions
